### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by tgamradt** [rithala/power-automate-tools#3]
I can't get the extension to work. Installed in Edge and opened a Power Automate Flow in edit mode. Clicking the extension icon only shows the five standard options like "Remove from Edge" etc.
Tried again in Chrome with the same results.

**Comment by rithala** [comment]
Hi, sorry for the very late response. I was away for a while. I tested the extension and it should work. Sometimes, it does not start from the edit view but the details view, the screen before going into edit mode :)

**Comment by tgamradt** [comment]
Hi, very late indeed :-)
I have to admit that I completely forgot about this. But the extension was still installed on my browser and it does work now. So whatever it is that went wrong a year ago seems to be ok now.
