### ISSUE TITLE
Keep getting invalid inputs property of type 'authentication'

### ISSUE THREAD

**Issue by ThreeTen22** [rithala/power-automate-tools#4]
Error during saving the flow definition: Error: Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowRunActionInputsInvalidProperty' and message 'The 'inputs' of workflow run action 'RefAccCol' of type 'OpenApiConnection' should not have the property 'authentication'.'."}}". Code: 0x80060467 InnerError: '.
Its unable to save any flows with dataverse connectors or any other action with the "authentication" property.

Full message:
Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'WorkflowRunActionInputsInvalidProperty' and message 'The 'inputs' of workflow run action 'RefAccCol' of type 'OpenApiConnection' should not have the property 'authentication'.'."}}".

**Comment by rithala** [comment]
The issue should be resolved by the 1.2 release.  Please check again after updating the extension.
